# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 09:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='Комментарий')),
                ('feedback_data', models.DateTimeField(null=True)),
                ('feedback_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='Keeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keep_title', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('keep_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('keep_data', models.DateTimeField(null=True)),
                ('keep_status', models.CharField(max_length=10, verbose_name='Статус статьи')),
            ],
            options={
                'db_table': 'keep',
            },
        ),
        migrations.CreateModel(
            name='KeeperStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keeper_status_text', models.CharField(max_length=100, verbose_name='Статус статьи')),
            ],
            options={
                'db_table': 'keeperstatus',
            },
        ),
        migrations.CreateModel(
            name='SearchLabelKeeper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchlabelkeeper_marker', models.CharField(max_length=200, unique=True, verbose_name='Поисковая метка')),
            ],
            options={
                'db_table': 'searchlabelkeeper',
            },
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions_text', models.TextField(verbose_name='Исправления')),
                ('suggestions_data', models.DateTimeField(null=True)),
                ('suggestions_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suggestions_keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keeper.Keeper')),
            ],
            options={
                'db_table': 'suggestions',
            },
        ),
        migrations.AddField(
            model_name='keeper',
            name='keep_hashTag',
            field=models.ManyToManyField(to='keeper.SearchLabelKeeper'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback_keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keeper.Keeper'),
        ),
    ]
