# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keeper',
            name='keep_status',
        ),
    ]
